use eyre::Context;
use serde::{Deserialize, Serialize};

use crate::protocol::v101::{ClientMessage, Message, Msgtype, NonceTo2ProveDv, NonceTo2SetupDv};

/// ```cddl
/// TO2.Done = [
///     NonceTO2ProveDv;; Nonce generated by Owner Onboarding Service
///                    ;; ...and sent to Device ROE in Msg TO2.ProveOVHdr
/// ]
/// ```
pub(crate) struct Done {
    pub(crate) nonce_to2_prove_dv: NonceTo2ProveDv,
}

impl Serialize for Done {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        let Self { nonce_to2_prove_dv } = self;

        (nonce_to2_prove_dv,).serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for Done {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let (nonce_to2_prove_dv,) = Deserialize::deserialize(deserializer)?;

        Ok(Self { nonce_to2_prove_dv })
    }
}

impl Message for Done {
    const MSG_TYPE: Msgtype = 70;

    fn decode(buf: &[u8]) -> eyre::Result<Self> {
        ciborium::from_reader(buf).wrap_err("couldn't decode TO2.Done")
    }

    fn encode(&self) -> eyre::Result<Vec<u8>> {
        let mut buf = Vec::new();

        ciborium::into_writer(self, &mut buf)?;

        Ok(buf)
    }
}

impl ClientMessage for Done {
    type Response<'a> = Done2;
}

/// ```cddl
/// TO2.Done = [
///     NonceTO2ProveDv;; Nonce generated by Owner Onboarding Service
///                    ;; ...and sent to Device ROE in Msg TO2.ProveOVHdr
/// ]
/// ```
pub(crate) struct Done2 {
    pub(crate) nonce_to2_setup_dv: NonceTo2SetupDv,
}

impl Serialize for Done2 {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        let Self { nonce_to2_setup_dv } = self;

        (nonce_to2_setup_dv,).serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for Done2 {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let (nonce_to2_setup_dv,) = Deserialize::deserialize(deserializer)?;

        Ok(Self { nonce_to2_setup_dv })
    }
}

impl Message for Done2 {
    const MSG_TYPE: Msgtype = 71;

    fn decode(buf: &[u8]) -> eyre::Result<Self> {
        ciborium::from_reader(buf).wrap_err("couldn't decode TO2.Done")
    }

    fn encode(&self) -> eyre::Result<Vec<u8>> {
        let mut buf = Vec::new();

        ciborium::into_writer(self, &mut buf)?;

        Ok(buf)
    }
}
