# Fedora
FROM fedora:42@sha256:fc97fe8dcec49820038e2cca5c8a4ca766b9a4b27cb85d7b8ceefef21491d476

WORKDIR /srv

RUN dnf --assumeyes install libtool awk automake autoconf autoconf-archive && \
    dnf --assumeyes group install development-tools c-development &&\
    dnf --assumeyes builddep tpm2-tss && \
    dnf --assumeyes install libuuid-devel

RUN git clone https://github.com/tpm2-software/tpm2-tss.git

ENTRYPOINT cd /srv/tpm2-tss && \
    ./bootstrap && ./configure --prefix="$PREFIX" && \
    make -j$(nproc) DESTDIR=/out CFLAGS="-Wno-error" && \
    make install
